apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-node-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nirajj-pal/sample-node-app-manifests.git
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-node-app-dev
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
