apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-node-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nirajj-pal/sample-node-app-manifests.git
    targetRevision: main
    path: overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-node-app-staging
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
