apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-node-app-dev
resources:
  - ../../base
images:
  - name: nirajpal/sample-node-app
    newTag: 10-3df5f3dd
commonLabels:
  environment: dev
patches:
  - target:
      kind: Deployment
      name: sample-node-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
