apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmsapi
  namespace: prod
  labels:
    app: cmsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmsapi
  template:
    metadata:
      labels:
        app: cmsapi
    spec:
      imagePullSecrets:
        - name: harbor-regcred
      containers:
        - name: cmsapi
          image: harbor.lr.in/project-lr/cmsapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
