apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: harbor.lr.in/project-lr/ordermutationmsapi
    newTag: d995db59
    newName: docker.io/nirajpal/sample-node-app
