apiVersion: v1
kind: Service
metadata:
  name: ordermutationmsapi
  namespace: dev
spec:
  selector:
    app: ordermutationmsapi
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP