apiVersion: v1
kind: Service
metadata:
  name: order-mutation-web-ms
  namespace: poc
spec:
  selector:
    app: order-mutation-web-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32523
  type: NodePort